@startuml

left to right direction

:Developer: as Dev
:Operation Manager: as Ops

rectangle "fleet"  #cccccc {
    (Manage Applications) as MA
    (Manage Clouds) as MC
    (Manage Hardware) as MH
    (Manage Vehicles) as MV
}

Dev --> MA
Ops --> MC
Ops --> MH
Ops --> MV

@enduml
